Lead_MS/Lead_MS/Models/ROLES.cs
namespace Lead_MS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity;
    using System.Data.Entity.Spatial;
    using System.Linq;

    public partial class ROLES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ROLES()
        {
            USUARIOS = new HashSet<USUARIOS>();
        }

        public int ID { get; set; }

        [Required]
        [StringLength(50)]
        public string NOMBRE { get; set; }

        [StringLength(255)]
        public string DESCRIPCION { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIOS> USUARIOS { get; set; }

        // METODO LISTAR
        public List<ROLES> Listar()
        {
            var roles = new List<ROLES>();
            try
            {
                using (var db = new ModeloLMS())
                {
                    roles = db.ROLES.ToList();
                }
            }
            catch (Exception ex)
            {
                throw new Exception("Error al listar los roles", ex);
            }

            return roles;
        }

        // METODO OBTENER
        public ROLES Obtener(int id)
        {
            ROLES rol = null;
            try
            {
                using (var db = new ModeloLMS())
                {
                    rol = db.ROLES.SingleOrDefault(x => x.ID == id);
                }
            }
            catch (Exception ex)
            {
                throw new Exception("Error al obtener el rol", ex);
            }

            return rol;
        }

        // METODO GUARDAR
        public void Guardar()
        {
            try
            {
                using (var db = new ModeloLMS())
                {
                    if (this.ID > 0)
                    {
                        db.Entry(this).State = EntityState.Modified;
                    }
                    else
                    {
                        db.ROLES.Add(this);
                    }
                    db.SaveChanges();
                }
            }
            catch (Exception ex)
            {
                throw new Exception("Error al guardar el rol", ex);
            }
        }

        // METODO ELIMINAR
        public void Eliminar()
        {
            try
            {
                using (var db = new ModeloLMS())
                {
                    db.Entry(this).State = EntityState.Deleted;
                    db.SaveChanges();
                }
            }
            catch (Exception ex)
            {
                throw new Exception("Error al eliminar el rol", ex);
            }
        }
    }
}

Lead_MS/Lead_MS/Controllers/RolesController.cs
using Lead_MS.Filters;
using Lead_MS.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lead_MS.Controllers
{
    //[Autenticado]
    public class RolesController : Controller
    {
        private ROLES objRol = new ROLES();

        // GET: Roles
        public ActionResult Index()
        {
            return View(objRol.Listar());
        }

        public ActionResult Visualizar(int id)
        {
            // Asegúrate de tener el using necesario para .Include
            using (var dbContext = new ModeloLMS())
            {
                // Reemplaza esta consulta con la que incluye ROLES
                var usuario = dbContext.USUARIOS.Include(u => u.ROLES).FirstOrDefault(u => u.ID == id);

                if (usuario == null)
                {
                    // Maneja el caso en que el usuario no se encuentre
                    return HttpNotFound();
                }

                return View(usuario);
            }
        }


        public ActionResult AgregarEditar(int id = 0)
        {
            return View(id == 0 ? new ROLES() : objRol.Obtener(id));
        }

        [HttpPost]
        public ActionResult Guardar(ROLES rol)
        {
            if (ModelState.IsValid)
            {
                rol.Guardar();
                return RedirectToAction("Index");
            }
            else
            {
                return View("AgregarEditar", rol);
            }
        }

        public ActionResult Eliminar(int id)
        {
            objRol.ID = id;
            objRol.Eliminar();
            return RedirectToAction("Index");
        }
    }
}

Lead_MS/Lead_MS/Views/Roles/AgregarEditar.cshtml
@model Lead_MS.Models.ROLES
@{
    ViewBag.Title = "AgregarEditar";
}

<div class="text-center">
    <h2>Agregar/Editar Rol</h2>
</div>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active"><a href="@Url.Action("Index", "Roles")">Roles</a></li>
        <li class="breadcrumb-item active" aria-current="page">@(Model.ID > 0 ? Model.NOMBRE : "Nuevo Registro")</li>
    </ol>
</nav>

<div class="card">
    <div class="card-header">
        Información del Rol
    </div>
    <div class="card-body">
        @using (Html.BeginForm("Guardar", "Roles", FormMethod.Post))
        {
            @Html.HiddenFor(x => x.ID)
            <div class="form-group">
                @Html.Label("Nombre")
                @Html.TextBoxFor(x => x.NOMBRE, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.NOMBRE, null, new { @class = "label label-danger" })
            </div>
            <div class="form-group">
                @Html.Label("Descripción")
                @Html.TextBoxFor(x => x.DESCRIPCION, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.DESCRIPCION, null, new { @class = "label label-danger" })
            </div>
            <div class="text-end">
                <button type="submit" class="btn btn-primary">Grabar</button>
                <a href="@Url.Action("Index", "Roles")" class="btn btn-danger">Cancelar</a>
            </div>
        }
    </div>
</div>

Lead_MS/Lead_MS/Views/Roles/Index.cshtml
@model List<Lead_MS.Models.ROLES>
@{
    ViewBag.Title = "Index";
}

<h2 class="card text-center">
    Mantenimiento de Roles
</h2>
<br />
<div class="text-start">
    <a href="@Url.Action("AgregarEditar", "Roles")" class="btn btn-success">Nuevo Rol</a>
</div>
<br />
<br />

<table class="table">
    <thead>
        <tr>
            <th style="width: 50px">Id</th>
            <th style="width: 150px">Nombre</th>
            <th style="width: 250px">Descripción</th>
            <th style="width: 250px">Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var rol in Model)
        {
            <tr>
                <td>@rol.ID</td>
                <td>@rol.NOMBRE</td>
                <td>@rol.DESCRIPCION</td>
                <td>
                    <a href="@Url.Action("Visualizar", "Roles", new { id = rol.ID })" class="btn btn-info">Visualizar</a>
                    <a href="@Url.Action("AgregarEditar", "Roles", new { id = rol.ID })" class="btn btn-warning">Modificar</a>
                    <a href="@Url.Action("Eliminar", "Roles", new { id = rol.ID })" class="btn btn-danger" onclick="return confirm('¿Está seguro de eliminar el registro?')">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Lead_MS/Lead_MS/Views/Roles/Visualizar.cshtml
@model Lead_MS.Models.ROLES
@{
    ViewBag.Title = "Visualizar Rol";
}

<div class="text-center">
    <h2>Visualizar Rol</h2>
</div>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active"><a href="@Url.Action("Index", "Roles")">Roles</a></li>
        <li class="breadcrumb-item active" aria-current="page">@Model.NOMBRE</li>
    </ol>
</nav>

<div class="card">
    <div class="card-header">
        Información del Rol
    </div>
    <div class="card-body">
        <dl class="list-group">
            <dt>ID</dt>
            <dd>@Model.ID</dd>
            <dt>Nombre</dt>
            <dd>@Model.NOMBRE</dd>
            <dt>Descripción</dt>
            <dd>@Model.DESCRIPCION</dd>
        </dl>
    </div>
</div>