Lead_MS/Lead_MS/Models/LEADS.cs
namespace Lead_MS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity;
    using System.Data.Entity.Spatial;
    using System.Linq;

    public partial class LEADS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LEADS()
        {
            ASIGNACIONES_LEAD = new HashSet<ASIGNACIONES_LEAD>();
            AUDITORIA_LEADS = new HashSet<AUDITORIA_LEADS>();
            CITAS = new HashSet<CITAS>();
            INTERACCIONES = new HashSet<INTERACCIONES>();
        }

        public int ID { get; set; }

        [Required]
        [StringLength(255)]
        public string NOMBRE { get; set; }

        [Required]
        [StringLength(255)]
        public string EMAIL { get; set; }

        [StringLength(50)]
        public string TELEFONO { get; set; }

        [StringLength(255)]
        public string EMPRESA { get; set; }

        [StringLength(255)]
        public string CARGO { get; set; }

        [Required]
        [StringLength(100)]
        public string FUENTE_ENTRADA { get; set; }

        public DateTime FECHA_CREACION { get; set; }

        [Required]
        [StringLength(50)]
        public string ESTADO { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASIGNACIONES_LEAD> ASIGNACIONES_LEAD { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUDITORIA_LEADS> AUDITORIA_LEADS { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CITAS> CITAS { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INTERACCIONES> INTERACCIONES { get; set; }

        //METODOS
        public List<LEADS> Listar()
        {
            var query = new List<LEADS>();
            try
            {
                using (var db = new ModeloLMS())
                {
                    query = db.LEADS.ToList();
                }
            }
            catch (Exception ex)
            {
                throw;
            }
            return query;

        }
        //Metodo obtener
        public LEADS Obtener(int id)
        {
            var query = new LEADS();
            try
            {
                using (var db = new ModeloLMS())
                {
                    query = db.LEADS.Where(x => x.ID == id).SingleOrDefault();
                }
            }
            catch (Exception ex)
            {
                throw;
            }
            return query;
        }

        //metodo buscar
        public List<LEADS> Buscar(string Buscar)
        {
            var query = new List<LEADS>();
            try
            {
                using (var db = new ModeloLMS())
                {
                    query = db.LEADS.Where(x => x.ID.ToString() == (Buscar) || x.NOMBRE.Contains(Buscar)).ToList();
                }
            }
            catch (Exception ex)
            {
                throw;
            }
            return query;

        }
        //metodo guardar
        public void Guardar()
        {
            try
            {
                using (var db = new ModeloLMS())
                {
                    if (this.ID > 0) //por existe en la bd
                    {
                        db.Entry(this).State = EntityState.Modified;
                    }
                    else //=0 no existe
                    //nuevo objeto agregar
                    {
                        db.Entry(this).State = EntityState.Added;
                    }
                    db.SaveChanges();
                }
            }
            catch (Exception ex)
            {
                throw;
            }
        }
        public void GuardarLP()
        {
            try
            {
                using (var db = new ModeloLMS())
                {
                    if (this.ID > 0) //por existe en la bd
                    {
                        db.Entry(this).State = EntityState.Modified;
                    }
                    else //=0 no existe
                    //nuevo objeto agregar
                    {
                        db.Entry(this).State = EntityState.Added;
                    }
                    db.SaveChanges();
                }
            }
            catch (Exception ex)
            {
                throw;
            }
        }
        //metodo eliminar
        public void Eliminar()
        {
            try
            {
                using (var db = new ModeloLMS())
                {
                    db.Entry(this).State = EntityState.Deleted;
                    db.SaveChanges();
                }
            }
            catch (Exception ex)
            {
                throw;
            }
        }
    }
}

Lead_MS/Lead_MS/Controllers/LeadsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lead_MS.Filters;
using Lead_MS.Models;

namespace Lead_MS.Controllers
{
    //[Autenticado]
    public class LeadsController : Controller
    {
        private LEADS objLead = new LEADS();

        // GET: LEADS
        public ActionResult Index(string Buscar)
        {
            if (string.IsNullOrEmpty(Buscar))
            {
                return View(objLead.Listar());
            }
            else
            {
                return View(objLead.Buscar(Buscar));
            }
        }

        public ActionResult Visualizar(int id)
        {
            return View(objLead.Obtener(id));
        }

        public ActionResult Buscar(string Buscar)
        {
            return View(
                string.IsNullOrEmpty(Buscar)
                ? objLead.Listar()
                : objLead.Buscar(Buscar)
            );
        }

        public ActionResult AgregarEditar(int id = 0)
        {
            return View(id == 0 ? new LEADS() : objLead.Obtener(id));
        }

        [HttpPost]
        public ActionResult Guardar(LEADS lead)
        {
            if (ModelState.IsValid)
            {
                if (lead.ID == 0)
                {
                    lead.FECHA_CREACION = DateTime.Now; // Solo asignar si es un nuevo lead
                }
                lead.Guardar();
                return RedirectToAction("Index");
            }
            else
            {
                return View("AgregarEditar", lead);
            }
        }

        public ActionResult Eliminar(int id)
        {
            objLead.ID = id;
            objLead.Eliminar();
            return RedirectToAction("Index");
        }
    }
}

Lead_MS/Lead_MS/Views/Leads/AgregarEditar.cshtml
@model Lead_MS.Models.LEADS
@{
    ViewBag.Title = "AgregarEditar";
}

<div class="text-center">
    <h2>Agregar/Editar Lead</h2>
</div>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active"><a href="~/Leads/Index">Leads</a></li>
        <li class="breadcrumb-item active" aria-current="page">@(Model.ID > 0 ? Model.NOMBRE : "Nuevo Registro")</li>
    </ol>
</nav>

<div class="card">
    <div class="card-header">
        Información del Lead
    </div>
    <div class="card-body">
        @using (Html.BeginForm("Guardar", "Leads", FormMethod.Post))
        {
            @Html.HiddenFor(x => x.ID)
            <div class="form-group">
                @Html.Label("Id")
                @Html.TextBoxFor(x => x.ID, new { @class = "form-control", disabled = true })
            </div>
            <div class="form-group">
                @Html.Label("Nombre")
                @Html.TextBoxFor(x => x.NOMBRE, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.NOMBRE, null, new { @class = "label label-danger" })
            </div>
            <div class="form-group">
                @Html.Label("Email")
                @Html.TextBoxFor(x => x.EMAIL, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.EMAIL, null, new { @class = "label label-danger" })
            </div>
            <div class="form-group">
                @Html.Label("Teléfono")
                @Html.TextBoxFor(x => x.TELEFONO, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.TELEFONO, null, new { @class = "label label-danger" })
            </div>
            <div class="form-group">
                @Html.Label("Empresa")
                @Html.TextBoxFor(x => x.EMPRESA, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.EMPRESA, null, new { @class = "label label-danger" })
            </div>
            <div class="form-group">
                @Html.Label("Cargo")
                @Html.TextBoxFor(x => x.CARGO, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.CARGO, null, new { @class = "label label-danger" })
            </div>
            <div class="form-group">
                @Html.Label("Fuente de Entrada")
                @Html.TextBoxFor(x => x.FUENTE_ENTRADA, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.FUENTE_ENTRADA, null, new { @class = "label label-danger" })
            </div>
            <div class="form-group">
                @Html.Label("Fecha de Creación")
                @Html.TextBoxFor(x => x.FECHA_CREACION, "{0:dd/MM/yyyy HH:mm:ss}", new { @class = "form-control", disabled = true })
            </div>
            <div class="form-group">
                @Html.Label("Estado")
                <select name="ESTADO" class="form-control">
                    <option @(Model.ESTADO == "" ? "selected" : "") value="">-Seleccione</option>
                    <option @(Model.ESTADO == "Nuevo" ? "selected" : "") value="Nuevo">-Nuevo</option>
                    <option @(Model.ESTADO == "En Proceso" ? "selected" : "") value="En Proceso">-En Proceso</option>
                    <option @(Model.ESTADO == "Cerrado" ? "selected" : "") value="Cerrado">-Cerrado</option>
                </select>
                @Html.ValidationMessageFor(x => x.ESTADO, null, new { @class = "label label-danger" })
            </div>
            <div class="text-end">
                <button type="submit" class="btn btn-primary">Grabar</button>
                <a href="~/Leads" class="btn btn-danger">Cancelar</a>
            </div>
        }
    </div>
</div>

Lead_MS/Lead_MS/Views/Leads/Index.cshtml
@model List<Lead_MS.Models.LEADS>
@{
    ViewBag.Title = "Index";
}

<h2 class="card text-center">
    Mantenimiento de Leads
</h2>
<br />
<div class="text-start">
    <a href="~/Leads/AgregarEditar/" class="btn btn-success">Nuevo Lead</a>
</div>
<br />
<br />

@using (Html.BeginForm("Index", "Leads", FormMethod.Post))
{
    <div class="text-end">
        @Html.Label("Buscar: ")
        @Html.TextBox("Buscar")
        <button type="submit" class="btn btn-dark">Buscar</button>
    </div>
}
<table class="table">
    <thead>
        <tr>
            <th style="width: 50px">ID</th>
            <th style="width: 150px">Nombre</th>
            <th style="width: 150px">Email</th>
            <th style="width: 100px">Teléfono</th>
            <th style="width: 100px">Empresa</th>
            <th style="width: 100px">Cargo</th>
            <th style="width: 100px">Fuente de Entrada</th>
            <th style="width: 100px">Fecha de Creación</th>
            <th style="width: 100px">Estado</th>
            <th style="width: 250px">Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var lead in Model)
        {
            <tr>
                <td>@lead.ID</td>
                <td>@lead.NOMBRE</td>
                <td>@lead.EMAIL</td>
                <td>@lead.TELEFONO</td>
                <td>@lead.EMPRESA</td>
                <td>@lead.CARGO</td>
                <td>@lead.FUENTE_ENTRADA</td>
                <td>@lead.FECHA_CREACION.ToString("dd/MM/yyyy")</td> <!-- Formato de fecha -->
                <td>@lead.ESTADO</td>
                <td>
                    <a href="~/Leads/Visualizar/@lead.ID" class="btn btn-info">Visualizar</a>
                    <a href="~/Leads/AgregarEditar/@lead.ID" class="btn btn-warning">Modificar</a>
                    <a href="~/Leads/Eliminar/@lead.ID" class="btn btn-danger" onclick="return confirm('¿Está seguro de eliminar el registro?')">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Lead_MS/Lead_MS/Views/Leads/Visualizar.cshtml
@model Lead_MS.Models.LEADS
@{
    ViewBag.Title = "Visualizar";
}

<div class="text-center">
    <h2>Visualizar Lead</h2>
</div>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active"><a href="~/Leads/Index">Leads</a></li>
        <li class="breadcrumb-item active" aria-current="page">@Model.NOMBRE</li>
    </ol>
</nav>

<div class="card">
    <div class="card-header">
        Información del Lead
    </div>
    <div class="card-body">
        <dl class="list-group-horizontal">
            <dt>ID</dt>
            <dd>@Model.ID</dd>
            <dt>Nombre</dt>
            <dd>@Model.NOMBRE</dd>
            <dt>Email</dt>
            <dd>@Model.EMAIL</dd>
            <dt>Teléfono</dt>
            <dd>@Model.TELEFONO</dd>
            <dt>Empresa</dt>
            <dd>@Model.EMPRESA</dd>
            <dt>Cargo</dt>
            <dd>@Model.CARGO</dd>
            <dt>Fuente de Entrada</dt>
            <dd>@Model.FUENTE_ENTRADA</dd>
            <dt>Fecha de Creación</dt>
            <dd>@Model.FECHA_CREACION.ToString("dd/MM/yyyy HH:mm:ss")</dd>
            <dt>Estado</dt>
            <dd>@Model.ESTADO</dd>
        </dl>
    </div>
</div>