Lead_MS/Lead_MS/Models/USUARIOS.cs
namespace Lead_MS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity;
    using System.Data.Entity.Spatial;
    using System.Linq;

    public partial class USUARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIOS()
        {
            ASIGNACIONES_LEAD = new HashSet<ASIGNACIONES_LEAD>();
            AUDITORIA_LEADS = new HashSet<AUDITORIA_LEADS>();
            CITAS = new HashSet<CITAS>();
        }

        public int ID { get; set; }

        [Required]
        [StringLength(255)]
        public string NOMBRE_USUARIO { get; set; }

        [Required]
        [StringLength(255)]
        public string HASH_CONTRASEÑA { get; set; }

        [Required]
        [StringLength(255)]
        public string EMAIL { get; set; }

        public int ROL_ID { get; set; }

        [StringLength(255)]
        public string AVATAR { get; set; }

        [StringLength(50)]
        public string TELEFONO { get; set; }

        [StringLength(255)]
        public string DESCRIPCION { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASIGNACIONES_LEAD> ASIGNACIONES_LEAD { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUDITORIA_LEADS> AUDITORIA_LEADS { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CITAS> CITAS { get; set; }

        public virtual ROLES ROLES { get; set; }

        //Implementacion de metodos

        // METODO LISTAR
        //public List<USUARIOS> Listar()
        //{
        //    var usuarios = new List<USUARIOS>();
        //    try
        //    {
        //        using (var db = new ModeloLMS())
        //        {
        //            usuarios = db.USUARIOS.ToList();
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        throw new Exception("Error al listar los usuarios", ex);
        //    }

        //    return usuarios;
        //}
        // METODO LISTAR CON ROLES
        public List<USUARIOS> Listar()
        {
            var usuarios = new List<USUARIOS>();
            try
            {
                using (var db = new ModeloLMS())
                {
                    usuarios = db.USUARIOS.Include(u => u.ROLES).ToList();
                }
            }
            catch (Exception ex)
            {
                throw new Exception("Error al listar los usuarios con roles", ex);
            }

            return usuarios;
        }

        // METODO OBTENER
        public USUARIOS Obtener(int id)
        {
            USUARIOS usuario = null;
            try
            {
                using (var db = new ModeloLMS())
                {
                    usuario = db.USUARIOS.Include(u => u.ROLES).SingleOrDefault(x => x.ID == id);
                }
            }
            catch (Exception ex)
            {
                throw new Exception("Error al obtener el usuario", ex);
            }

            return usuario;
        }


        // METODO BUSCAR
        public List<USUARIOS> Buscar(string criterio)
        {
            var usuarios = new List<USUARIOS>();
            try
            {
                using (var db = new ModeloLMS())
                {
                    usuarios = db.USUARIOS
                        .Where(x => x.NOMBRE_USUARIO.Contains(criterio) || x.EMAIL.Contains(criterio))
                        .ToList();
                }
            }
            catch (Exception ex)
            {
                throw new Exception("Error al buscar usuarios", ex);
            }

            return usuarios;
        }
        // METODO BUSCAR CON ROLES
        public List<USUARIOS> BuscarConRoles(string criterio)
        {
            var usuarios = new List<USUARIOS>();
            try
            {
                using (var db = new ModeloLMS())
                {
                    usuarios = db.USUARIOS
                        .Include(u => u.ROLES)
                        .Where(x => x.NOMBRE_USUARIO.Contains(criterio) || x.EMAIL.Contains(criterio))
                        .ToList();
                }
            }
            catch (Exception ex)
            {
                throw new Exception("Error al buscar usuarios con roles", ex);
            }

            return usuarios;
        }

        // METODO GUARDAR
        public void Guardar()
        {
            try
            {
                using (var db = new ModeloLMS())
                {
                    if (this.ID > 0)
                    {
                        db.Entry(this).State = EntityState.Modified;
                    }
                    else
                    {
                        db.USUARIOS.Add(this);
                    }
                    db.SaveChanges();
                }
            }
            catch (Exception ex)
            {
                throw new Exception("Error al guardar el usuario", ex);
            }
        }

        // METODO ELIMINAR
        public void Eliminar()
        {
            try
            {
                using (var db = new ModeloLMS())
                {
                    db.Entry(this).State = EntityState.Deleted;
                    db.SaveChanges();
                }
            }
            catch (Exception ex)
            {
                throw new Exception("Error al eliminar el usuario", ex);
            }
        }

        // METODO VALIDAR LOGIN
        public ResponseModel ValidarLogin(string Usuario, string Password)
        {
            var rm = new ResponseModel();
            try
            {
                using (var db = new ModeloLMS())
                {
                    Password = HashHelper.MD5(Password);

                    var usuario = db.USUARIOS.Where(x => x.NOMBRE_USUARIO == Usuario)
                                             .Where(x => x.HASH_CONTRASEÑA == Password)
                        .SingleOrDefault();

                    if (usuario != null)
                    {
                        SessionHelper.AddUserToSession(usuario.ID.ToString());
                        rm.SetResponse(true);
                    }
                    else
                    {
                        rm.SetResponse(false, "Usuario o contraseña incorrectos");
                    }
                }
            }
            catch (Exception ex)
            {
                throw new Exception("Error al validar el login", ex);
            }

            return rm;
        }

        // METODO GUARDAR PERFIL
        //public ResponseModel GuardarPerfil(HttpPostedFileBase foto)
        //{
        //    var rm = new ResponseModel();
        //    try
        //    {
        //        using (var db = new ModeloLMS())
        //        {
        //            db.Configuration.ValidateOnSaveEnabled = false;
        //            var usuario = db.Entry(this);
        //            usuario.State = EntityState.Modified;

        //            if (foto != null)
        //            {
        //                string extension = Path.GetExtension(foto.FileName).ToLower();
        //                int size = 1024 * 1024 * 5;
        //                var filtro = new[] { ".jpg", ".png", ".jpeg", ".gif" };

        //                if (filtro.Contains(extension) && (foto.ContentLength <= size))
        //                {
        //                    string archivo = Path.GetFileName(foto.FileName);
        //                    foto.SaveAs(HttpContext.Current.Server.MapPath("~/Uploads/" + archivo));
        //                    this.AVATAR = archivo;
        //                }
        //            }
        //            else
        //            {
        //                usuario.Property(x => x.AVATAR).IsModified = false;
        //            }

        //            db.SaveChanges();
        //            rm.SetResponse(true);
        //        }
        //    }
        //    catch (DbEntityValidationException ex)
        //    {
        //        throw new Exception("Error de validación de entidad", ex);
        //    }
        //    catch (Exception ex)
        //    {
        //        throw new Exception("Error al guardar el perfil", ex);
        //    }

        //    return rm;
        //}
    }
}

Lead_MS/Lead_MS/Controllers/UsuariosController.cs
using Lead_MS.Filters;
using Lead_MS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lead_MS.Controllers
{
    //[Autenticado]
    public class UsuariosController : Controller
    {
        private USUARIOS objUsuario = new USUARIOS();
        private ROLES objRol = new ROLES();

        // GET: Usuarios
        public ActionResult Index(string Buscar)
        {
            var usuarios = string.IsNullOrEmpty(Buscar)
                ? objUsuario.Listar()
                : objUsuario.BuscarConRoles(Buscar);

            return View(usuarios);
        }

        public ActionResult Visualizar(int id)
        {
            var usuario = objUsuario.Obtener(id);
            return View(usuario);
        }

        public ActionResult Buscar(string Buscar)
        {
            return View(
                string.IsNullOrEmpty(Buscar)
                ? objUsuario.Listar()
                : objUsuario.BuscarConRoles(Buscar)
            );
        }

        public ActionResult AgregarEditar(int id = 0)
        {
            ViewBag.Roles = objRol.Listar();
            return View(id == 0 ? new USUARIOS() : objUsuario.Obtener(id));
        }

        [HttpPost]
        public ActionResult Guardar(USUARIOS usuario)
        {
            if (ModelState.IsValid)
            {
                usuario.Guardar();
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Roles = objRol.Listar();
                return View("AgregarEditar", usuario);
            }
        }

        public ActionResult Eliminar(int id)
        {
            objUsuario.ID = id;
            objUsuario.Eliminar();
            return RedirectToAction("Index");
        }
    }
}

Lead_MS/Lead_MS/Views/Usuarios/AgregarEditar.cshtml
@model Lead_MS.Models.USUARIOS
@{
    ViewBag.Title = "AgregarEditar";
    var roles = new SelectList(ViewBag.Roles as List<Lead_MS.Models.ROLES>, "ID", "NOMBRE", Model.ROL_ID);
}

<div class="text-center">
    <h2>Agregar/Editar Usuario</h2>
</div>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active"><a href="~/Usuarios/Index">Usuarios</a></li>
        <li class="breadcrumb-item active" aria-current="page">@(Model.ID > 0 ? Model.NOMBRE_USUARIO : "Nuevo Registro")</li>
    </ol>
</nav>

<div class="card">
    <div class="card-header">
        Información del Usuario
    </div>
    <div class="card-body">
        @using (Html.BeginForm("Guardar", "Usuarios", FormMethod.Post))
        {
            @Html.HiddenFor(x => x.ID)
            <div class="form-group">
                @Html.LabelFor(x => x.NOMBRE_USUARIO)
                @Html.TextBoxFor(x => x.NOMBRE_USUARIO, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.NOMBRE_USUARIO, null, new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.HASH_CONTRASEÑA)
                @Html.PasswordFor(x => x.HASH_CONTRASEÑA, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.HASH_CONTRASEÑA, null, new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.Label("Confirmar Contraseña")
                <input type="password" class="form-control" id="ConfirmarContraseña" name="ConfirmarContraseña" />
                <span class="text-danger" id="ContraseñaError" style="display:none;">Las contraseñas no coinciden.</span>
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.EMAIL)
                @Html.TextBoxFor(x => x.EMAIL, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.EMAIL, null, new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.TELEFONO)
                @Html.TextBoxFor(x => x.TELEFONO, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.TELEFONO, null, new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.DESCRIPCION)
                @Html.TextAreaFor(x => x.DESCRIPCION, new { @class = "form-control", rows = 3 })
                @Html.ValidationMessageFor(x => x.DESCRIPCION, null, new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.ROL_ID, "Rol")
                @Html.DropDownListFor(x => x.ROL_ID, roles, "-Seleccione un Rol-", new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.ROL_ID, null, new { @class = "text-danger" })
            </div>
            <br />
            <div class="text-end">
                <button type="submit" class="btn btn-primary" onclick="return validarContraseña();">Grabar</button>
                <a href="~/Usuarios" class="btn btn-danger">Cancelar</a>
            </div>
        }
    </div>
</div>

<script type="text/javascript">
    function validarContraseña() {
        var contraseña = document.getElementById("HASH_CONTRASEÑA").value;
        var confirmarContraseña = document.getElementById("ConfirmarContraseña").value;
        if (contraseña !== confirmarContraseña) {
            document.getElementById("ContraseñaError").style.display = "block";
            return false;
        }
        return true;
    }
</script>

Lead_MS/Lead_MS/Views/Usuarios/Index.cshtml
@model List<Lead_MS.Models.USUARIOS>
@{
    ViewBag.Title = "Index";
}

<h2 class="card text-center">
    Mantenimiento de Usuarios
</h2>
<br />
<div class="text-start">
    <a href="~/Usuarios/AgregarEditar/" class="btn btn-success">Nuevo Usuario</a>
</div>
<br />
<br />

@using (Html.BeginForm("Index", "Usuarios", FormMethod.Post))
{
    <div class="text-end">
        @Html.Label("Buscar: ")
        @Html.TextBox("Buscar", null, new { @class = "form-control d-inline-block", style = "width: 200px;" })
        <button type="submit" class="btn btn-dark">Buscar</button>
    </div>
}
<br />
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th style="width: 50px">Id</th>
            <th style="width: 150px">Nombre Usuario</th>
            <th style="width: 150px">Email</th>
            <th style="width: 150px">Teléfono</th>
            <th style="width: 150px">Descripción</th>
            <th style="width: 150px">Rol</th>
            <th style="width: 250px">Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var usuario in Model)
        {
            <tr>
                <td>@usuario.ID</td>
                <td>@usuario.NOMBRE_USUARIO</td>
                <td>@usuario.EMAIL</td>
                <td>@usuario.TELEFONO</td>
                <td>
                    <!-- Botón para ver la descripción -->
                    <a href="~/Usuarios/Visualizar/@usuario.ID" class="btn btn-primary">Ver Descripción</a>
                </td>
                <td>
                    @if (usuario.ROLES != null)
                    {
                        <text>@usuario.ROLES.NOMBRE</text>
                    }
                    else
                    {
                        <text>Sin Rol</text>
                    }
                </td>
                <td>
                    <a href="~/Usuarios/Visualizar/@usuario.ID" class="btn btn-info">Visualizar</a>
                    <a href="~/Usuarios/AgregarEditar/@usuario.ID" class="btn btn-warning">Modificar</a>
                    <a href="~/Usuarios/Eliminar/@usuario.ID" class="btn btn-danger" onclick="return confirm('¿Está seguro de eliminar el registro?')">Eliminar</a>
                </td>
            </tr>
        }

    </tbody>
</table>

Lead_MS/Lead_MS/Views/Usuarios/Visualizar.cshtml
@model Lead_MS.Models.USUARIOS
@{
    ViewBag.Title = "Visualizar Usuario";
}

<div class="text-center">
    <h2>Visualizar Usuario</h2>
</div>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active"><a href="~/Usuarios/Index">Usuarios</a></li>
        <li class="breadcrumb-item active" aria-current="page">@Model.NOMBRE_USUARIO</li>
    </ol>
</nav>

<div class="card">
    <div class="card-header">
        Información del Usuario
    </div>
    <div class="card-body">
        <dl class="list-group">
            <dt>ID</dt>
            <dd>@Model.ID</dd>
            <dt>Nombre de Usuario</dt>
            <dd>@Model.NOMBRE_USUARIO</dd>
            <dt>Email</dt>
            <dd>@Model.EMAIL</dd>
            <dt>Teléfono</dt>
            <dd>@Model.TELEFONO</dd>
            <dt>Descripción</dt>
            <dd>@Model.DESCRIPCION</dd>
            <dt>Rol</dt>
            <dd>@(Model.ROLES != null ? Model.ROLES.NOMBRE : "Sin Rol")</dd>

        </dl>
    </div>
</div>